---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "酒類在庫取得・検索API"
host: "localhost:8080"
basePath: "/api/v1"
schemes:
  - "http"
paths:
  /liquors:
    get:
      summary: "酒類在庫取得API"
      operationId: "liquors_get"
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/GetRecordsResponse"
        "500":
          description: "never mind"
      x-swagger-router-controller: "controllers.default_controller"

  /liquors/add:
    # ToDo:追加機能実装の際はpostに変える
    get:
      summary: "酒類在庫追加API"
      operationId: "liquors_add"
      parameters:
        [
          {
            name: "liquorName",
            in: "query",
            description: "liquor's name",
            type: "string",
          },
          {
            name: "sellerName",
            in: "query",
            description: "seller's name",
            type: "string",
          },
          {
            name: "isReservable",
            in: "query",
            description: "reservable or not",
            type: "string",
          },
          {
            name: "arrivalDay",
            in: "query",
            description: "ariival date",
            type: "string",
          },
          {
            name: "reserveScore",
            in: "query",
            description: "number of reservation",
            type: "string",
          },
        ]
      responses:
        "200":
          description: "OK"
          schema:
            type: "boolean"
        "500":
          description: "never mind"
      x-swagger-router-controller: "controllers.default_controller"

  /liquors/search/{liquorName}:
    get:
      summary: "酒類在庫検索API"
      operationId: "liquors_search"
      parameters:
        - in: "path"
          name: "liquorName"
          type: string
          required: true
      responses:
        "200":
          description: "OK"
      x-swagger-router-controller: "controllers.default_controller"

    post:
      summary: "酒類在庫取り置きAPI"
      operationId: "liquors_reserve"
      parameters:
        - in: "path"
          name: "liquorName"
          type: string
          required: true
      responses:
        "200":
          description: "OK"
      x-swagger-router-controller: "controllers.default_controller"

definitions:
  PostRecordsRequest:
    type: "object"
    required:
      - "value"
    properties:
      value:
        type: "integer"
    xml:
      name: "Pet"

  GetRecordsResponse:
    type: "boolean"
    # items:
    #   type: "object"
    #   properties:
    #     liquorCollection:
    #       type: "string"
    #       example: "sake"
    # liquorName:
    #   type: "string"
    #   example: "sake"
    # sellerName:
    #   type: "string"
    #   example: "ivis"
    # isReservable:
    #   type: "string"
    #   example: "false"
    # arrivalDay:
    #   type: "string"
    #   example: "2020/12/25"
    # reserveScore:
    #   type: "string"
    #   example: "1"
