---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "酒類在庫取得・検索API"
host: "localhost:8080"
basePath: "/api/v1"
schemes:
  - "http"
paths:
  /liquors:
    get:
      summary: "酒類在庫取得API"
      operationId: "liquors_get"
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/GetRecordsResponse"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"

  /liquors/{liquorName}:
    get:
      summary: "酒類在庫検索API"
      operationId: "liquors_search"
      parameters:
        - in: "path"
          name: "liquorName"
          type: string
          required: true
      responses:
        "200":
          description: "OK"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"

    post:
      summary: "酒類在庫取り置きAPI"
      operationId: "liquors_reserve"
      parameters:
        - in: "path"
          name: "liquorName"
          type: string
          required: true
      responses:
        "200":
          description: "OK"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"

definitions:
  PostRecordsRequest:
    type: "object"
    required:
      - "value"
    properties:
      value:
        type: "integer"
    xml:
      name: "Pet"

  GetRecordsResponse:
    type: "array"
    items:
      type: "integer"
