# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
import util


class PostRecordsRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, value: int = None):  # noqa: E501
        """PostRecordsRequest - a model defined in Swagger

        :param value: The value of this PostRecordsRequest.  # noqa: E501
        :type value: int
        """
        self.swagger_types = {
            'value': int
        }

        self.attribute_map = {
            'value': 'value'
        }

        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'PostRecordsRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PostRecordsRequest of this PostRecordsRequest.  # noqa: E501
        :rtype: PostRecordsRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> int:
        """Gets the value of this PostRecordsRequest.


        :return: The value of this PostRecordsRequest.
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value: int):
        """Sets the value of this PostRecordsRequest.


        :param value: The value of this PostRecordsRequest.
        :type value: int
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value
